In [1]:
import numpy as np

In [2]:
#!pip install numpy

In [3]:
#https://jalammar.github.io/visual-numpy/

In [4]:
my_list = [1,2,3,4,5,6]

In [5]:
type(my_list)

list

In [6]:
np.array(my_list)

array([1, 2, 3, 4, 5, 6])

In [7]:
my_numpy_array = np.array(my_list)

In [8]:
type(my_numpy_array)

numpy.ndarray

In [10]:
my_numpy_array.max()

np.int64(6)

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.random.random(5)

array([0.54937771, 0.59632538, 0.08892684, 0.25629472, 0.55241854])

In [14]:
# Array arithmetic

In [15]:
my_list1 = [1,2]

In [16]:
my_list2 = [2,3]

In [17]:
my_list1 + my_list2

[1, 2, 2, 3]

In [18]:
my_numpy_array1 = np.array(my_list1)

In [19]:
my_numpy_array2 = np.array(my_list2)

In [20]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [21]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [22]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [23]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [24]:
my_numpy_array1 * 5

array([ 5, 10])

In [27]:
my_list1 * 5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [28]:
my_numpy_array.sum()

np.int64(21)

In [29]:
# arrange & indexing

In [30]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
np_array = np.arange(0,10)

In [34]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np_array[0]

np.int64(0)

In [36]:
np_array[-1]

np.int64(9)

In [37]:
np_array[1:4:]

array([1, 2, 3])

In [38]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [39]:
np_array[2:6:2]

array([2, 4])

In [40]:
# random

In [41]:
np.random.randn(4)

array([0.6204505 , 1.39063404, 0.09463109, 0.09610707])

In [42]:
np.random.randn(4,4)

array([[-0.74621021, -0.20416315,  0.34338334,  0.56914162],
       [-0.033725  ,  0.24727632, -0.79134187, -0.54678093],
       [-1.17909334,  0.28858214,  2.03361467,  0.15866433],
       [ 0.25153936, -0.44497348,  0.80405347, -0.60823993]])

In [43]:
np.random.randint(1,300,5)

array([ 53, 214, 194,  58, 133], dtype=int32)