In [1]:
import numpy as np

In [5]:
my_matrix = [[5,10],[15,20]]

In [6]:
my_matrix[0][1]

10

In [4]:
# row * column

In [7]:
numpy_matrix = np.array([[5,10],[15,20]])

In [8]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [9]:
numpy_matrix[1][0]

np.int64(15)

In [10]:
numpy_matrix.sum()

np.int64(50)

In [11]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.random.random((3,2))

array([[0.35932938, 0.01156716],
       [0.27112072, 0.76134927],
       [0.45922603, 0.37227505]])

In [14]:
# matrix arithmetic

In [15]:
first_array = np.array([[10,20],[30,40]])

In [16]:
second_array = np.array([[5,15],[25,35]])

In [17]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [18]:
first_array

array([[10, 20],
       [30, 40]])

In [28]:
third_array  = np.array([50,60])
third_array.shape

(2,)

In [25]:
first_array + third_array # broadcasting

array([[ 60,  80],
       [ 80, 100]])

In [36]:
fourth_array = np.array([[10,20,30,40,50]])
fourth_array.shape

(1, 5)

In [37]:
## first_array + fourth_array ## not working, cannot make broadcasting

In [38]:
 # matrix multiplication

In [39]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [40]:
# dot product

In [41]:
first_matrix = np.array([[10,20,30]])

In [42]:
first_matrix.shape

(1, 3)

In [46]:
first_matrix

array([[10, 20, 30]])

In [43]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [44]:
second_matrix.shape

(3, 2)

In [47]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [45]:
# first_matrix * second_matrix wouldn't work

In [ ]:
result_matrix = first_matrix.dot(second_matrix)