In [1]:
import numpy as np

In [2]:
new_array = np.random.randint(1,100,20)

In [3]:
new_array

array([69, 89, 30, 22, 34, 81, 90, 56, 79, 75, 54,  4, 40, 83,  6, 56, 79,
       85, 68, 67], dtype=int32)

In [4]:
new_array > 25

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True])

In [5]:
new_array[new_array > 25]

array([69, 89, 30, 34, 81, 90, 56, 79, 75, 54, 40, 83, 56, 79, 85, 68, 67],
      dtype=int32)

In [6]:
# transpose & reshape

In [7]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [8]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [9]:
matrix_array.shape

(3, 2)

In [10]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [11]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [12]:
random_array = np.random.random((6,1))

In [13]:
random_array

array([[0.89624202],
       [0.54815314],
       [0.41534694],
       [0.4600315 ],
       [0.47481809],
       [0.80369638]])

In [14]:
random_array.shape

(6, 1)

In [15]:
random_array.reshape(2,3)

array([[0.89624202, 0.54815314, 0.41534694],
       [0.4600315 , 0.47481809, 0.80369638]])

In [16]:
random_array.reshape(3,2)

array([[0.89624202, 0.54815314],
       [0.41534694, 0.4600315 ],
       [0.47481809, 0.80369638]])

In [17]:
# z-score

In [18]:
data = np.array([10,12,13,15,18,25,100,105])

In [19]:
# outlier

In [20]:
mean = np.mean(data)

In [21]:
mean

np.float64(37.25)

In [22]:
data.sum() / len(data)

np.float64(37.25)

In [23]:
std = np.std(data)

In [24]:
std

np.float64(37.9333296719389)

In [28]:
z_scores = (data - mean) / std

In [29]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [30]:
z_scores[z_scores>1]

array([1.65421809, 1.78602829])

In [31]:
data[z_scores>1]

array([100, 105])

In [32]:
# math equations

In [33]:
# 2x + 3y = 8 and 5x + 7y = 19

In [34]:
# coefficient

In [37]:
A = np.array([[2,3],[5,7]])

In [38]:
# constant

In [39]:
b = np.array([8,19])

In [40]:
solution = np.linalg.solve(A,b)

In [41]:
solution

array([1., 2.])